### ISSUE TITLE
Memory access error on localization selection

### ISSUE THREAD

**Issue by kevinsbarnard** [mbari-media-management/cthulhu#22]
When selecting a list of localizations, Cthulhu is erroring with `java.lang.Error: Invalid memory access`, causing the player window to freeze.

Excerpt from Cthulhu log:

```
10:06:07.473 [Thread-5                 ] DEBUG o.m.c.u.c.a.AnnotationImageView          | select(annotations=[88e4110f-94b7-4a11-a8ff-59856b758526, 454fd457-da67-4642-a981-1309a3f9f9d9, dd3a86f3-366f-4665-a78b-77271b7a785c, 07c91263-1824-4e50-afbd-6a0461ec227a, daa13537-6454-43ab-a3bd-862c46bee464, d99cfb74-f57c-4fef-ad07-4a2f84dcb13b, aa0782c2-3346-4f33-8553-2f98bf8c69b1, e899b16d-2960-4688-9c80-74a6ca0c4465, 5867623e-60e5-4677-abeb-24816b91f19d, 144a1f97-382b-4a55-8a8f-98b1a839f069, 6992b402-0a15-446a-bcb9-f2bee3cd5304, ec7b88b4-78d7-48dd-bee8-82b9850b5831, 1ef24d32-a314-4683-9468-2c5faab94bd1, 40273225-ad3d-4f9a-8751-109f03f51acf, 2710aebc-adcb-4a65-983b-0d91c4fe924b, fbb3f289-f3a8-459e-97dd-82fa7a449f16, e4687b91-b75b-40b0-87bf-fa3884af155e, b68d5886-265a-4f30-8be5-5ab3d0ba9468, 6e58417d-eb06-483b-876e-92f98ae4bf08, 92f5b8e1-2a88-4573-b16e-9c76d8e329c8, 42fe0966-9876-4509-a5d4-4e9f4331145b, 828b4b94-3e50-4b50-a694-eacad5b4daea, 2ec73cb4-61ad-44fd-9151-aac73ebeb260, f7e245d3-79e8-449c-91f5-e3798ef206b9, d1897cd8-1dae-42fa-b466-5772d48a3185, 39323b4c-00d9-45cd-9914-5da2a29adcfc, 131c3cbe-ccf3-4cdf-8e66-a4a83ebfd7b0, fb648e1a-a7e3-45aa-ae9b-7c006e2c4193, edbc6bc5-fcf0-47db-bdbd-9da299af62bd, 02537898-4c9a-4887-a697-474ee983adcb, 8cd74116-2486-46d3-aa95-70abe3b93759, 148f6d64-e371-45a6-bf50-50d8cabf3fce, e3589138-72ac-4450-93ce-c6080fb65518, 72b54a1e-665c-40eb-912c-a0ee5cfad274, f82b6288-5ae9-4109-92c7-349c9f28aa29, 493708eb-bb9f-465c-b7d6-bf383d4c6966, 346868e2-7dcb-46ed-9862-9ea4b274228e, 1150b155-042a-4a70-848d-53893b5d9f55, aa328ecc-c9d7-45f6-ab9b-bc09c2528679, a87521eb-c42c-4c01-b554-de6299bd38d2, 69436a8e-b7ec-49f0-95bd-aced1ffdaf9c, 3f70d970-ecfe-4c77-b0ab-122c0c45cfea, ed1dd7cc-6559-4bc2-8251-08363be442fa, 16639e83-ae91-4659-8cfb-3c5cf9e9bde3, 298d54b2-dd57-4847-9e38-a514b944d3ae, 9e00bb99-be0e-4caa-ba49-cd74beb8ac0a, 0c693bc1-0cd3-4c3d-a15c-851b9a5f6fe0, bebe36b9-38e8-425d-9536-ed519ce2c2df, 1e73b8af-535c-47be-831b-0e2fdb6b9cae, 32f50af0-dc4a-46f5-a9ec-a6b6b8a8d254, 07688e96-4ab8-48a7-8f3e-ae5834224e9f, ddf7afe0-5ede-48c8-b19f-007a1df3d1de, b1927e31-4093-46a3-93e9-7cc9dfdaec71, 8ce4fbb8-bd93-4685-a8e7-32dc15cd3546, 5b12c88a-6a0a-4ddb-835f-7a9af47ee0c4, 2523db9e-47b5-48e1-886b-09f245cb7887, 00bd76c9-eb0a-447c-af7c-d6e4a77b3ca9, 8a3cc566-aa13-4ed6-bf88-1dc4f98c8692, 4a3f22a0-6cfe-46e5-ba13-6a0014646fe2, 6e7c93a7-7f83-41d0-9a3d-a91ca561e8db, 9fea8214-7d02-468a-a192-1aa7a0770176, a650d64b-e31a-440f-8548-80b6d7ea2132, 72c78320-86d1-418e-8c1c-0dde00cbd18e, 1e57a0a1-7d83-4e51-a0cf-188facce1d3b, a43d358b-aa10-45dc-ac5b-eca54130d324, b65af18b-322e-46e1-bc25-c945dd4e11cb, 310b96d4-27b9-4960-bd56-2329aed6154c, 4990a95f-333d-4de9-a5c3-8c260cd9053c, cf3f7480-8204-4624-882b-8cf5ac0413f3, 464ebefc-17f0-43ec-a205-ff8441eeb040, f1bae1ce-b876-4b01-aeb3-c35585e1294c, 2738118e-06d1-47fe-b2b4-e2ee2ed55903, 772cbc9c-ac6d-4b97-a7f3-bb2fcab67b94, 2661a7d9-8a7e-4d48-a15d-1ce02e821fd0, 02bd5dd9-9753-4178-8fd0-037db0e265eb, 5261b6f2-a86b-4aed-a36c-3ee596b7cf4a, bc504a5f-4d77-449f-96ae-9d9da6c7ba82, b881bcd2-d96c-4894-87f9-ced0cf20266e, 45f9ea43-3f1e-4432-8e0e-c02f3051f14f, 6d2cbfef-924e-43ef-9fe5-404c7950a225, 233ac009-1d4c-4a31-b610-fdd40e5708a6, 06a7f761-cba7-4837-aa9b-ab0b7b11955a, 91faba78-90c4-4bac-bfbd-56a02f845ef3, 23afd8c5-b1f9-4470-a51a-7fb903921280, e6b02a8b-7083-4eac-815c-c230f5ebeaf7, 428c3e14-d952-4cba-8069-97ec7c79d487, 3a2d657d-c064-4437-b6a3-8a8bbc67c0b1, 42e8193b-51b3-42bf-9e27-c003b941cfc6, 81e854f7-250e-42bc-8361-483f15b539fa, 346c250e-5c63-4c64-8958-87c0c09c6561, 322419f7-b3ce-4930-b5e1-c2f8bfacfc39, 5e421540-a804-469c-87bb-66d1844230be, d64ad884-72a0-47bf-8871-c3bdbb6b3b02, 798aaa03-1412-4b30-9e8d-cf642cc06198, c3684433-5811-42cb-aa2c-3883b508f8cd, c018de12-7fba-44f8-b6d2-56a5d471f49f, 43fd4070-83a5-47dc-9d23-bdd7a59f844e, 1e69dcc8-a8a5-49a9-b462-1c9a9c892b6e, a5a1cb3f-383a-4100-b18d-7f34ec16f268, 27eb81d4-a5d0-4c9c-941b-759d0987335d, c1dc9986-5a9f-4a65-a8ab-628f7b27c5be, 352de5e4-82f6-43a5-ac8d-3963676b58b8, 5c3f6aa2-9cfb-4daa-8afd-5e333f1fe43b, 3869cac2-5b09-4b08-b718-a77ad0bc0211, 5b884cfc-c6af-4cea-aed4-00942bdeee58, 33040c71-7875-4eed-9dd1-f4f5cae79e0c, f102d5cf-10c4-4299-8544-fd2510d803c4, 47ca40b1-f920-42ac-83fe-557d43ffe5c1, 2281e9a4-83a1-449a-9be8-c9992ec2cbe9, 4564d88c-5466-4720-9a91-bb74e0751e54, ac92332f-ab21-4fdb-a553-4d7e55d8c8dd, 1f019356-f376-4726-91f8-6fcba35930a9, 95210f91-f6a1-4238-a05e-6003337b0d3c, 6012a002-f983-4573-aba9-9f7b469f52cd, 4033a439-0e63-489d-b96e-87837abd0922, 7a4fff65-bc60-4260-8c7d-a05a7bc4c41c, 50d523d2-3c68-45a7-b88a-60359799bb50, d86987b2-5877-4bdc-b2f7-4c21e579ec2b, 9e417970-bf19-40b5-895e-c0a4eceba724, 3921911d-9e62-44e0-bf6f-a2ebc8e13ff0, 3b87d0e1-70fa-4bf2-8d1e-4444959fe669, edf4daf9-6e86-4d92-b42e-0770a948106f, aede9b1f-b009-411a-92bd-9807e4f08d76])
Exception in thread "JavaFX Application Thread" java.lang.Error: Invalid memory access
        at vlcj.natives@4.1.0/uk.co.caprica.vlcj.binding.LibVlc.libvlc_media_player_is_playing(Native Method)
        at uk.co.caprica.vlcj@4.7.2/uk.co.caprica.vlcj.player.base.StatusApi.isPlaying(StatusApi.java:60)
        at org.mbari.cthulhu@1.0.0/org.mbari.cthulhu.ui.components.annotationview.AnnotationImageView.startBoxEditHandling(AnnotationImageView.java:311)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
        at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by kevinsbarnard** [comment]
This happens on Windows but not macOS, so not too pressing at the moment.

**Comment by hohonuuli** [comment]
@kevinsbarnard can you note the commit that you're seeing this issue on?

**Comment by kevinsbarnard** [comment]
@hohonuuli Yes, I originally ran into this on the `dissapearing-boxes` branch, commit fffadaf2f265d6b42b32f4caf3caf3aabe8c8e09, but this also happens on `master`, commit e5e1eb6695a4db5aa9a91ca73d059c3fe1589030
